/**
 * Create the list of all build-in flying squid plugins so the frontend
 * doesn't need to access directory listings
 *
 * Based on https://github.com/PrismarineJS/flying-squid/blob/master/src/lib/requireindex.js
 */
const fs = require("fs");
const path = require("path");

function getFileList(dir) {
  const requires = [];
  const files = fs.readdirSync(dir);

  // Sort files in lowercase alpha for Linux
  files.sort((a, b) => {
    a = a.toLowerCase();
    b = b.toLowerCase();

    if (a < b) {
      return -1;
    } else if (b < a) {
      return 1;
    } else {
      return 0;
    }
  });

  files.forEach((filename) => {
    // Ignore `index.js` and files prefixed with underscore and
    if (filename === "index.js" || filename[0] === "_" || filename[0] === ".") {
      return;
    }

    const filepath = path.resolve(path.join(dir, filename));
    const ext = path.extname(filename);
    const stats = fs.statSync(filepath);

    // Don't require non-javascript files (.txt, .md, etc.)
    if (stats.isFile() && ![".js", ".node", ".json"].includes(ext)) {
      return;
    }

    const basename = path.basename(filename, ext);
    requires.push(basename);
  });

  return requires;
}

const flyingSquidPluginDirectory = path.resolve(
  __dirname,
  "../node_modules/flying-squid/src/lib/plugins"
);
const fileList = getFileList(flyingSquidPluginDirectory);

const outputFile = path.resolve(
  __dirname,
  "../src/classes/minecraftServer/buildInPlugins.ts"
);
const output = `// This file is generated by the createPluginList.js script.
// Do not edit this file directly.
export default {
${fileList
  .map(
    (plugin) =>
      `  ${plugin}: () => import("flying-squid/src/lib/plugins/${plugin}")`
  )
  .join(",\n")}
};
`;
fs.writeFileSync(outputFile, output);

console.log(`Wrote ${fileList.length} plugins to ${outputFile}`);
